---
- name: Install required apt packages
  become: true
  apt:
    name: git
    state: present

- name: Install required pip packages
  become: true
  pip:
    name: docker
    state: present

- name: Check if mailcow installation directory exists
  become: true
  stat:
    path: "{{ mailcow__install_path }}"
  register: mailcow_installed

- name: Clone mailcow git repo
  become: true
  git:
    repo: '{{ mailcow__git_url }}'
    version: "{{ mailcow__git_version }}"
    umask: '022'
    update: false
    dest: "{{ mailcow__install_path }}"
  when: not mailcow_installed.stat.exists

- name: Generate mailcow.conf file
  shell: ./generate_config.sh
  environment:
    MAILCOW_HOSTNAME: "{{ mailcow__hostname }}"
    MAILCOW_TZ: "{{ mailcow__timezone }}"
  args:
    executable: /bin/bash
    chdir: "{{ mailcow__install_path }}"
    creates: mailcow.conf
  tags:
    - skip_ansible_lint

- name: Template settings for mailcow.conf
  become: true
  import_tasks: mailcowconf.yml

- name: Template settings for Nginx
  become: true
  import_tasks: nginx.yml

- name: Copy vars.local.inc.php
  become: true
  template:
    src: vars.local.inc.php.j2
    dest: "{{ mailcow__install_path }}/data/web/inc/vars.local.inc.php"

- name: Template docker-compose override
  template:
    src: docker-compose.override.yml.j2
    dest: "{{ mailcow__install_path }}/docker-compose.override.yml"
  when: mailcow__override_volumes is defined

- name: Check if mailcow is running
  become: true
  docker_container_info:
    name: "{{ mailcow__docker_compose_project_name }}_nginx-mailcow_1"
  register: mailcow_running

- name: Start mailcow stack
  become: true
  docker_compose:
    project_src: "{{ mailcow__install_path }}"
    project_name: "{{ mailcow__docker_compose_project_name }}"
    state: present
    build: false
    pull: true
  when: not mailcow_running.exists

- name: Update mailcow
  include_tasks: update.yml
  when:
    - mailcow_running.exists
    - mailcow__install_updates
